
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Copy, CheckCircle, FileText, ArrowLeft } from "lucide-react";
import { motion } from "framer-motion";

export default function GeneratedPrompts({ prompts, onStartOver }) {
  const [copiedIndex, setCopiedIndex] = useState(null);

  const copyToClipboard = async (text, index) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-white/10 backdrop-blur-lg border-white/20">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <CardTitle className="text-2xl font-bold text-white flex items-center gap-3">
                <FileText className="w-7 h-7 text-blue-400" />
                {prompts.deliverable_name}
              </CardTitle>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center space-x-2 opacity-70">
                <span className="text-xs text-blue-300">Generated by</span>
                <img 
                  src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/199aedeea_FinalRepeatableLogowithoutbackground1.png"
                  alt="Repeatable AI"
                  className="h-5 w-auto"
                />
              </div>
              <Button
                variant="ghost"
                onClick={onStartOver}
                className="bg-white/10 border border-white/20 text-white hover:bg-white/20"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Choose Another
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-blue-200 text-lg leading-relaxed">
            {prompts.overview}
          </p>
        </CardContent>
      </Card>

      {/* Prompts */}
      <div className="space-y-4">
        {prompts.prompts.map((prompt, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
          >
            <Card className="bg-white/10 backdrop-blur-lg border-white/20 hover:bg-white/15 transition-all duration-200">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Badge className="bg-gradient-to-r from-blue-500 to-purple-600 text-white">
                      Step {prompt.step}
                    </Badge>
                    <CardTitle className="text-lg text-white">
                      {prompt.title}
                    </CardTitle>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => copyToClipboard(prompt.prompt, index)}
                    className="bg-white/10 border border-white/20 text-white hover:bg-white/20"
                  >
                    {copiedIndex === index ? (
                      <>
                        <CheckCircle className="w-4 h-4 mr-2 text-green-400" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4 mr-2" />
                        Copy
                      </>
                    )}
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-blue-200">
                  {prompt.description}
                </p>
                <div className="bg-gray-900/50 rounded-lg p-4 border border-white/10">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-gray-400 font-mono">COPY THIS PROMPT</span>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => copyToClipboard(prompt.prompt, index)}
                      className="text-gray-400 hover:text-white h-6 px-2"
                    >
                      <Copy className="w-3 h-3" />
                    </Button>
                  </div>
                  <pre className="text-sm text-gray-100 whitespace-pre-wrap font-mono leading-relaxed">
                    {prompt.prompt}
                  </pre>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Instructions */}
      <Card className="bg-white/10 backdrop-blur-lg border-white/20">
        <CardContent className="p-6">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-white font-bold flex items-center gap-2">
              <FileText className="w-5 h-5 text-blue-400" />
              How to Use These Prompts
            </h3>
            <img 
              src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/199aedeea_FinalRepeatableLogowithoutbackground1.png"
              alt="Repeatable AI"
              className="h-6 w-auto opacity-60"
            />
          </div>
          <div className="space-y-2 text-blue-100">
            <p>• Copy each prompt in sequential order and paste them into the LLM of your choice. Input or upload the context and knowledge files as requested by the generated prompts. If you do not have the requested submissions, don't worry, just tell AI to proceed without it or ask AI to generate "Synthetic Data" common to the requested deliverable.</p>
            <p>• Use the output from each step to inform the next</p>
            <p>• Customize the prompts based on your specific needs</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
