/**
 * Working Deliverable Flow (B.4)
 *
 * Displays 3-7 copy-paste prompt chunks generated by Claude.
 * User copies each chunk and runs it externally.
 */

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { apiClient } from '@/api/apiClient';
import { SavedPrompt } from '@/api/entities';
import { useToast } from '@/components/ui/use-toast';
import {
  Copy,
  Check,
  Loader2,
  ArrowLeft,
  Download,
} from 'lucide-react';
import { downloadMarkdown } from '@/lib/downloadMarkdown';
import PerplexityPromptStep from './PerplexityPromptStep';

export default function WorkingDeliverableFlow({ company, deliverable, sessionZeroDossier, onBack, onComplete }) {
  const { toast } = useToast();

  // Perplexity step state — shown before chunk generation
  const [phase, setPhase] = useState('perplexity'); // 'perplexity' | 'chunks'
  const [perplexityBrief, setPerplexityBrief] = useState(null);

  const [isLoading, setIsLoading] = useState(false);
  const [chunks, setChunks] = useState([]);
  const [copiedChunks, setCopiedChunks] = useState(new Set());
  const [error, setError] = useState('');

  // Start chunk generation when entering 'chunks' phase
  useEffect(() => {
    if (phase === 'chunks' && chunks.length === 0) {
      generateChunks();
    }
  }, [phase]);

  const generateChunks = async () => {
    setIsLoading(true);
    setError('');

    try {
      const result = await apiClient.request('/deliverable/working', {
        method: 'POST',
        body: JSON.stringify({
          companyId: company.id,
          deliverableName: deliverable.name,
          deliverableType: deliverable.type,
          category: deliverable.column || deliverable.category,
          description: deliverable.description || deliverable.name,
        }),
      });

      const generatedChunks = result.chunks || [];
      setChunks(generatedChunks);

      // Auto-save the generated prompts — include dossier if available
      try {
        const allPrompts = [];

        // Step 0: Session 00 Dossier (if generated)
        if (sessionZeroDossier) {
          allPrompts.push({
            step: 0,
            title: 'Session 00 — Company Dossier',
            description: 'Paste this dossier into your Claude session first — it provides the company context for everything that follows.',
            prompt: sessionZeroDossier,
          });
        }

        // Perplexity Research Brief (if generated)
        if (perplexityBrief) {
          allPrompts.push({
            step: allPrompts.length,
            title: 'Perplexity Deep Research Brief',
            description: 'Copy this into Perplexity deep research. Bring the results back into your Claude session before running the prompts below.',
            prompt: perplexityBrief,
          });
        }

        // Working mode chunks
        const offset = allPrompts.length;
        generatedChunks.forEach((chunk, i) => {
          allPrompts.push({
            step: offset + (chunk.number || i + 1),
            title: chunk.purpose || `Chunk ${chunk.number || i + 1}`,
            description: `Chunk ${chunk.number || i + 1} of ${chunk.total || generatedChunks.length}`,
            prompt: chunk.content || '',
          });
        });

        await SavedPrompt.create(company.id, {
          deliverable_name: deliverable.name,
          deliverable_type: deliverable.type,
          column_name: deliverable.column || deliverable.category || null,
          overview: `Working mode — ${generatedChunks.length} prompt chunks for ${deliverable.name}`,
          prompts: allPrompts,
          is_custom: deliverable.isCustom || false,
          custom_input: deliverable.isCustom ? deliverable.name : null,
        });
      } catch (saveErr) {
        console.error('WorkingDeliverableFlow: failed to save prompts:', saveErr);
      }
    } catch (err) {
      setError(err.message || 'Failed to generate chunks');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = async (chunk) => {
    try {
      await navigator.clipboard.writeText(chunk.content);
      setCopiedChunks(prev => new Set(prev).add(chunk.number));
      toast({ title: `Chunk ${chunk.number} copied`, duration: 2000 });
    } catch {
      toast({ title: 'Copy failed — try selecting manually', variant: 'destructive' });
    }
  };


  // ── Perplexity Step ──────────────────────────────────────

  if (phase === 'perplexity') {
    return (
      <div className="max-w-3xl mx-auto space-y-4">
        {/* Header */}
        <div>
          <Button variant="ghost" onClick={onBack} className="text-blue-300 hover:text-white mb-2 -ml-2">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Matrix
          </Button>
          <h2 className="text-xl font-bold text-white">{deliverable.name}</h2>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-xs px-2 py-0.5 bg-blue-500/20 border border-blue-500/30 rounded-full text-blue-300">
              Working Mode
            </span>
          </div>
        </div>

        <PerplexityPromptStep
          company={company}
          deliverable={deliverable}
          onGenerated={(brief) => {
            setPerplexityBrief(brief);
            setPhase('chunks');
          }}
          onSkip={() => setPhase('chunks')}
        />
      </div>
    );
  }

  // ── Loading ──────────────────────────────────────────────

  if (isLoading) {
    return (
      <div className="max-w-3xl mx-auto flex flex-col items-center justify-center py-20">
        <Loader2 className="w-10 h-10 text-blue-400 animate-spin mb-4" />
        <p className="text-blue-300 font-medium">Generating prompt chunks...</p>
        <p className="text-blue-200/50 text-sm mt-1">
          Claude is analyzing the deliverable and producing 3-7 copy-paste prompts.
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-3xl mx-auto">
        <div className="p-4 bg-red-500/20 border border-red-500/50 rounded-lg text-red-300 mb-4">{error}</div>
        <Button variant="outline" onClick={onBack} className="text-white border-white/20">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Matrix
        </Button>
      </div>
    );
  }

  // ── Render ───────────────────────────────────────────────

  return (
    <div className="max-w-3xl mx-auto space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <Button variant="ghost" onClick={onBack} className="text-blue-300 hover:text-white mb-2 -ml-2">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Matrix
          </Button>
          <h2 className="text-xl font-bold text-white">{deliverable.name}</h2>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-xs px-2 py-0.5 bg-blue-500/20 border border-blue-500/30 rounded-full text-blue-300">
              Working Mode
            </span>
            <span className="text-blue-200/50 text-xs">
              {chunks.length} chunks
            </span>
          </div>
        </div>
      </div>

      {/* Session 00 — Generated Dossier (first prompt if no user files) */}
      {sessionZeroDossier && (
        <Card className="bg-purple-500/5 border-purple-500/30">
          <CardContent className="p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono bg-purple-500/20 px-2 py-0.5 rounded text-purple-300">
                  Session 00
                </span>
                <span className="text-white text-sm font-medium">Company Dossier</span>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={async () => {
                    try {
                      await navigator.clipboard.writeText(sessionZeroDossier);
                      toast({ title: 'Session 00 Dossier copied', duration: 2000 });
                    } catch {
                      toast({ title: 'Copy failed', variant: 'destructive' });
                    }
                  }}
                  className="text-purple-300 border-purple-500/30 hover:bg-purple-500/10"
                >
                  <Copy className="w-3 h-3 mr-1" /> Copy
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => downloadMarkdown(sessionZeroDossier, company?.name || 'Company-Dossier')}
                  className="text-purple-300 border-purple-500/30 hover:bg-purple-500/10"
                >
                  <Download className="w-3 h-3 mr-1" /> Download
                </Button>
              </div>
            </div>
            <p className="text-blue-200/60 text-xs">
              Paste this dossier into your Claude session first — it provides the company context for all subsequent prompts.
            </p>
            <pre className="text-xs text-blue-200/70 bg-black/30 p-3 rounded overflow-x-auto overflow-y-auto whitespace-pre-wrap font-mono">
              {sessionZeroDossier}
            </pre>
          </CardContent>
        </Card>
      )}

      {/* Chunk Cards */}
      {chunks.map((chunk) => (
        <Card
          key={chunk.number}
          className="border bg-white/5 border-white/10"
        >
          <CardContent className="p-4 space-y-3">
            {/* Chunk header */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono bg-white/10 px-2 py-0.5 rounded text-blue-300">
                  {chunk.number}/{chunk.total}
                </span>
                <span className="text-white text-sm font-medium">{chunk.purpose}</span>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => handleCopy(chunk)}
                  className="text-blue-300 border-white/20 hover:bg-white/10"
                >
                  {copiedChunks.has(chunk.number) ? (
                    <><Check className="w-3 h-3 mr-1" /> Copied</>
                  ) : (
                    <><Copy className="w-3 h-3 mr-1" /> Copy</>
                  )}
                </Button>
              </div>
            </div>

            {/* Content preview */}
            <pre className="text-xs text-blue-200/70 bg-black/30 p-3 rounded overflow-x-auto overflow-y-auto whitespace-pre-wrap font-mono">
              {chunk.content}
            </pre>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
