/**
 * Working Deliverable Flow (B.4)
 *
 * Displays 3-7 copy-paste prompt chunks generated by Claude.
 * User copies each chunk, runs it, marks complete, then handles
 * the final ACD/Registry user-elect decision.
 */

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import {
  RadioGroup,
  RadioGroupItem,
} from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { apiClient } from '@/api/apiClient';
import { useToast } from '@/components/ui/use-toast';
import {
  Copy,
  Check,
  Loader2,
  AlertTriangle,
  ArrowLeft,
  FileUp,
  ClipboardCheck,
  Sparkles,
} from 'lucide-react';

export default function WorkingDeliverableFlow({ company, deliverable, sessionZeroDossier, onBack, onComplete }) {
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(true);
  const [chunks, setChunks] = useState([]);
  const [completedChunks, setCompletedChunks] = useState(new Set());
  const [copiedChunks, setCopiedChunks] = useState(new Set());
  const [acdChoice, setAcdChoice] = useState('C');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  const allComplete = chunks.length > 0 && completedChunks.size === chunks.length;
  const hasSequenceComplete = chunks.some(c => c.isSequenceComplete);

  useEffect(() => {
    generateChunks();
  }, []);

  const generateChunks = async () => {
    setIsLoading(true);
    setError('');

    try {
      const result = await apiClient.request('/deliverable/working', {
        method: 'POST',
        body: JSON.stringify({
          companyId: company.id,
          deliverableName: deliverable.name,
          deliverableType: deliverable.type,
          category: deliverable.column || deliverable.category,
          description: deliverable.description || deliverable.name,
        }),
      });

      setChunks(result.chunks || []);
    } catch (err) {
      setError(err.message || 'Failed to generate chunks');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = async (chunk) => {
    try {
      await navigator.clipboard.writeText(chunk.content);
      setCopiedChunks(prev => new Set(prev).add(chunk.number));
      toast({ title: `Chunk ${chunk.number} copied`, duration: 2000 });
    } catch {
      toast({ title: 'Copy failed — try selecting manually', variant: 'destructive' });
    }
  };

  const toggleChunkComplete = (chunkNumber) => {
    setCompletedChunks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(chunkNumber)) {
        newSet.delete(chunkNumber);
      } else {
        newSet.add(chunkNumber);
      }
      return newSet;
    });
  };

  const handleSubmitCompletion = async () => {
    setIsSubmitting(true);
    try {
      await apiClient.request('/deliverable/working/complete', {
        method: 'POST',
        body: JSON.stringify({
          companyId: company.id,
          deliverableName: deliverable.name,
          acdRegistryChoice: acdChoice,
        }),
      });

      const choiceLabels = { A: 'ACD generated', B: 'Logged to registry', C: 'ACD + registry', D: 'Skipped' };
      toast({
        title: 'Deliverable Complete',
        description: choiceLabels[acdChoice],
        duration: 3000,
      });

      if (onComplete) onComplete(acdChoice);
    } catch (err) {
      toast({ title: 'Error', description: err.message, variant: 'destructive' });
    } finally {
      setIsSubmitting(false);
    }
  };

  // ── Loading ──────────────────────────────────────────────

  if (isLoading) {
    return (
      <div className="max-w-3xl mx-auto flex flex-col items-center justify-center py-20">
        <Loader2 className="w-10 h-10 text-blue-400 animate-spin mb-4" />
        <p className="text-blue-300 font-medium">Generating prompt chunks...</p>
        <p className="text-blue-200/50 text-sm mt-1">
          Claude is analyzing the deliverable and producing 3-7 copy-paste prompts.
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-3xl mx-auto">
        <div className="p-4 bg-red-500/20 border border-red-500/50 rounded-lg text-red-300 mb-4">{error}</div>
        <Button variant="outline" onClick={onBack} className="text-white border-white/20">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Matrix
        </Button>
      </div>
    );
  }

  // ── Render ───────────────────────────────────────────────

  return (
    <div className="max-w-3xl mx-auto space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <Button variant="ghost" onClick={onBack} className="text-blue-300 hover:text-white mb-2 -ml-2">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Matrix
          </Button>
          <h2 className="text-xl font-bold text-white">{deliverable.name}</h2>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-xs px-2 py-0.5 bg-blue-500/20 border border-blue-500/30 rounded-full text-blue-300">
              Working Mode
            </span>
            <span className="text-blue-200/50 text-xs">
              {chunks.length} chunks — {completedChunks.size} of {chunks.length} complete
            </span>
          </div>
        </div>
      </div>

      {/* Session 00 — Generated Dossier (first prompt if no user files) */}
      {sessionZeroDossier && (
        <Card className="bg-purple-500/5 border-purple-500/30">
          <CardContent className="p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono bg-purple-500/20 px-2 py-0.5 rounded text-purple-300">
                  Session 00
                </span>
                <span className="text-white text-sm font-medium">Company Dossier</span>
              </div>
              <Button
                size="sm"
                variant="outline"
                onClick={async () => {
                  try {
                    await navigator.clipboard.writeText(sessionZeroDossier);
                    toast({ title: 'Session 00 Dossier copied', duration: 2000 });
                  } catch {
                    toast({ title: 'Copy failed', variant: 'destructive' });
                  }
                }}
                className="text-purple-300 border-purple-500/30 hover:bg-purple-500/10"
              >
                <Copy className="w-3 h-3 mr-1" /> Copy
              </Button>
            </div>
            <p className="text-blue-200/60 text-xs">
              Paste this dossier into your Claude session first — it provides the company context for all subsequent prompts.
            </p>
            <pre className="text-xs text-blue-200/70 bg-black/30 p-3 rounded overflow-x-auto max-h-48 overflow-y-auto whitespace-pre-wrap font-mono">
              {sessionZeroDossier.substring(0, 500)}{sessionZeroDossier.length > 500 ? '...' : ''}
            </pre>
          </CardContent>
        </Card>
      )}

      {/* Chunk Cards */}
      {chunks.map((chunk) => (
        <Card
          key={chunk.number}
          className={`border transition-all ${
            completedChunks.has(chunk.number)
              ? 'bg-green-500/5 border-green-500/30'
              : 'bg-white/5 border-white/10'
          }`}
        >
          <CardContent className="p-4 space-y-3">
            {/* Chunk header */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono bg-white/10 px-2 py-0.5 rounded text-blue-300">
                  {chunk.number}/{chunk.total}
                </span>
                <span className="text-white text-sm font-medium">{chunk.purpose}</span>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => handleCopy(chunk)}
                  className="text-blue-300 border-white/20 hover:bg-white/10"
                >
                  {copiedChunks.has(chunk.number) ? (
                    <><Check className="w-3 h-3 mr-1" /> Copied</>
                  ) : (
                    <><Copy className="w-3 h-3 mr-1" /> Copy</>
                  )}
                </Button>
              </div>
            </div>

            {/* MCQ Warning */}
            {chunk.containsMcq && (
              <div className="flex items-center gap-2 p-2 bg-amber-500/10 border border-amber-500/30 rounded text-amber-300 text-xs">
                <AlertTriangle className="w-4 h-4 flex-shrink-0" />
                This chunk contains an MCQ — complete it before advancing.
              </div>
            )}

            {/* Content preview */}
            <pre className="text-xs text-blue-200/70 bg-black/30 p-3 rounded overflow-x-auto max-h-48 overflow-y-auto whitespace-pre-wrap font-mono">
              {chunk.content.substring(0, 500)}{chunk.content.length > 500 ? '...' : ''}
            </pre>

            {/* Complete checkbox */}
            <div className="flex items-center gap-2 pt-1">
              <Checkbox
                id={`chunk-${chunk.number}`}
                checked={completedChunks.has(chunk.number)}
                onCheckedChange={() => toggleChunkComplete(chunk.number)}
              />
              <label htmlFor={`chunk-${chunk.number}`} className="text-sm text-blue-200/70 cursor-pointer">
                I've run this chunk
              </label>
            </div>
          </CardContent>
        </Card>
      ))}

      {/* Completion Panel */}
      {allComplete && (
        <Card className="bg-purple-500/5 border-purple-500/30">
          <CardContent className="p-6 space-y-4">
            <div className="flex items-center gap-2 text-purple-300 font-semibold">
              <ClipboardCheck className="w-5 h-5" />
              All Chunks Complete
            </div>

            <p className="text-blue-200/70 text-sm">
              This deliverable is complete. What would you like to do?
            </p>

            <RadioGroup value={acdChoice} onValueChange={setAcdChoice} className="space-y-2">
              <div className="flex items-center gap-2">
                <RadioGroupItem value="A" id="choice-a" />
                <Label htmlFor="choice-a" className="text-white text-sm">(A) Generate companion ACD</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="B" id="choice-b" />
                <Label htmlFor="choice-b" className="text-white text-sm">(B) Log to artifact registry</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="C" id="choice-c" />
                <Label htmlFor="choice-c" className="text-white text-sm">(C) Both</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="D" id="choice-d" />
                <Label htmlFor="choice-d" className="text-white text-sm">(D) Skip</Label>
              </div>
            </RadioGroup>

            <Button
              onClick={handleSubmitCompletion}
              disabled={isSubmitting}
              className="w-full bg-purple-600 hover:bg-purple-700 text-white"
            >
              {isSubmitting ? (
                <Loader2 className="w-4 h-4 animate-spin mr-2" />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              Complete Deliverable
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
